version: 1.0.{build}
os:
- Visual Studio 2015

install:
  - git submodule update --init --recursive
  - ps: ./install_maven.ps1
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5\

cache:
  - C:\sonarqube\downloads -> appveyor.yml
  - C:\users\appveyor\.m2 -> appveyor.yml

configuration: Release

before_build:
  - nuget restore
  
build:
  verbosity: minimal
  project: SonarQube.Scanner.MSBuild.sln
 
on_success:
  - ps: ./appveyor_on_success.ps1

on_finish:
# Uncomment this to be able to RDP into the build agent
# ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

