# SonarScanner for MSBuild
# Build, QA, Deploy

schedules:
# Run from Monday to Friday at 2:0 UTC (https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#cron-syntax)
- cron: "0 2 * * 1-5"
  displayName: Nightly build
  branches:
    include:
    - master
  always: true

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - group: sonarsource-build-variables

resources:
  repositories:
    - repository: commonTemplates
      type: git
      name: pipelines-yaml-templates
      ref: refs/tags/v1.0.11

stages:
- template: stage-with-burgr-notifications.yml@commonTemplates
  parameters:
    burgrName: 'qa'
    burgrType: 'qa'
    stageName: 'qa'
    stageDisplayName: 'QA:'
    jobs:
    - job: net6_its
      displayName: 'Run .NET 6 ITs'
      variables:
        MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
        MAVEN_OPTS: '-Xmx3072m -Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
        SQ_VERSION: "LATEST_RELEASE[7.9]"
        SONAR_CFAMILYPLUGIN_VERSION: "LATEST_RELEASE"
        SONAR_CSHARPPLUGIN_VERSION: "LATEST_RELEASE"
        SONAR_VBNETPLUGIN_VERSION: "LATEST_RELEASE"
        MSBUILD_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe"
        PLATFORMTOOLSET: "v140"
        WINDOWSSDKTARGET: "10.0.17763.0"
      pool:
        vmImage: "ubuntu-latest"
      container: mcr.microsoft.com/dotnet/sdk:6.0
      steps:
       - checkout: self
         fetchDepth: 1
       ## This JDK11 task uses hardcoded java version that is
       ## - downloaded from github release for VS image 2015 (because JDK8 is installed by default, and we need 11+ to run DEV / LTS7.9+)
       ## - Defined as per the java version installed and not used by default for VS2017 image (see : https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md)
       - task: CmdLine@2
         inputs:
           script: 'apt-get install openjdk-11-jdk'
       - task: JavaToolInstaller@0
         inputs:
           versionSpec: '11'
           jdkArchitectureOption: 'x64'
           jdkSourceOption: 'PreInstalled'
       - task: PowerShell@2
         displayName: "Write JDK11 path to JDK_PATH"
         inputs:
          targetType: 'inline'
          script: |
               Write-Host "##vso[task.setvariable variable=JDK_PATH]$JAVA_HOME"
       - task: NuGetToolInstaller@1
         inputs:
          versionSpec: '5.8.0'
       - task: PowerShell@2
         displayName: "Get version from artifact file"
         inputs:
          targetType: 'inline'
          script: |
             $projectVersion = Get-Content "$(Pipeline.Workspace)\\scanner-packages\\version.txt"
             Write-Host "##vso[task.setvariable variable=SONAR_PROJECT_VERSION]$projectVersion"
       - task: Maven@3
         displayName: 'Run Maven ITs for SQ $(SQ_VERSION)_$(imageName)'
         env:
           ARTIFACTORY_QA_READER_USERNAME: $(ARTIFACTORY_QA_READER_USERNAME)
           ARTIFACTORY_QA_READER_PASSWORD: $(ARTIFACTORY_QA_READER_PASSWORD)
           # For Orchestrator
           ARTIFACTORY_API_KEY: $(ARTIFACTORY_API_KEY)
           GITHUB_TOKEN: $(GITHUB_TOKEN)
           MAVEN_LOCAL_REPOSITORY: $(MAVEN_CACHE_FOLDER)
           NUGET_PATH: $(NUGETEXETOOLPATH)
         inputs:
          goals: 'verify'
          options: --settings $(mavenSettings.secureFilePath) -B -e -Denable-repo=qa -Dsonar.cfamilyplugin.version=$(SONAR_CFAMILYPLUGIN_VERSION) -Dsonar.csharpplugin.version=$(SONAR_CSHARPPLUGIN_VERSION) -Dsonar.vbnetplugin.version=$(SONAR_VBNETPLUGIN_VERSION) -Dsonar.runtimeVersion=$(SQ_VERSION) -DscannerForMSBuild.version=$(SONAR_PROJECT_VERSION).$(Build.BuildId) -Dmsbuild.path="$(MSBUILD_PATH)" -Dmsbuild.plateformtoolset=$(PLATFORMTOOLSET) -Dmsbuild.windowssdk=$(WINDOWSSDKTARGET)
          publishJUnitResults: true
          mavenPomFile: 'its/pom.xml'
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          testRunTitle: 'ITs $(SQ_VERSION)_$(imageName)'
          javaHomeOption: 'Path'
          jdkDirectory: $(JAVA_HOME_11_X64)
          mavenOptions: $(MAVEN_OPTS)
          mavenVersionOption: 'Default'
       - bash: git checkout .
         name: revertPomChanges
         displayName: Revert changes made to pom.xml to not break cache feature
