name: Milestone Issue

on:
  issues:
    types: ["milestoned"]

jobs:
  CreateCardForMilestonedIssue_job:
    name: Create card
    runs-on: ubuntu-latest
    # Single quotes must be used here https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#literals
    if: github.event.issue.state != 'closed'

    steps:
      - uses: sonarsource/gh-action-lt-backlog/CreateCardForIssue@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          column-id: 6183855     # Kanban "To do" column
