name: sonar-release
# This workflow is triggered when publishing a new github release
on:
  release:
    types:
      - published

env:
  PYTHONUNBUFFERED: 1

jobs:
  sonar_release:
    runs-on: ubuntu-latest
    name: Start release process
    steps:
      - name: Scanner release
        id: scanner_release
        with:
          publish_to_binaries: true
          attach_artifacts_to_github_release: false
          run_rules_cov: false
          slack_channel: scanner-guild
        env:
          ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
          BURGRX_USER: ${{ secrets.BURGRX_USER }}
          BURGRX_PASSWORD: ${{ secrets.BURGRX_PASSWORD }}
          CIRRUS_TOKEN: ${{ secrets.CIRRUS_TOKEN }}
          PATH_PREFIX: ${{ secrets.BINARIES_PATH_PREFIX }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          RELEASE_SSH_USER: ${{ secrets.RELEASE_SSH_USER }}
          RELEASE_SSH_KEY: ${{ secrets.RELEASE_SSH_KEY }}
          SLACK_API_TOKEN: ${{secrets.SLACK_API_TOKEN }}
        uses: SonarSource/gh-action_release/main@v3

      - name: Release action results
        if: always()
        run: |
          echo "${{ steps.lt_release.outputs.releasability }}"
          echo "${{ steps.lt_release.outputs.release }}"
