name: release
on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Setup JFrog
        uses: SonarSource/jfrog-setup-wrapper@3.2.4
        with:
          artifactoryRoleSuffix: promoter
      - name: Get the version
        id: get_version
        run: |
          IFS=. read major minor patch build <<< "${{ github.event.release.tag_name }}"
          echo "build=${build}" >> $GITHUB_OUTPUT
      - name: Promote Artifact
        id: jfrog
        run: |
          jfrog rt bpr --status released sonar-scanner-msbuild ${{ steps.get_version.outputs.build }} sonarsource-public-releases
