# .github/workflows/slack_notify.yml
---
name: Slack Notifications
on:
 check_run:
  types: [rerequested, completed]

jobs:
 slack-notifications:
  permissions:
   id-token: write  # to authenticate via OIDC
  uses: SonarSource/gh-action_build-notify/.github/workflows/main.yaml@v1
  if: >-
    github.event.check_run.name == 'SonarScanner for MSBuild'
    || endsWith(github.event.check_run.name, 'SonarCloud Code Analysis')
  with:
    slackChannel: squad-dotnet-s4net
